server:
  port: 8081

university:
  academicHoursPerDay: 3
  daysPerWeek: 5

timetable:
  generation:
    algorithm:
      genetics:
        populationSize: 1000
        #5%, 1%, 0.1% etc.
        mutation-rate: 5
