server:
  port: 8081

university:
  academicHoursPerDay: 3
  daysPerWeek: 5

timetable:
  generation:
    algorithm:
      genetics:
        populationSize: 9
        crossover-rate: 0.9
        tournament-selection-size: 3
        elite-chromosomes-number: 1
        mutation-rate: 0.1
