server:
  port: 8081

university:
  academicHoursPerDay: 3
  daysPerWeek: 5

timetable:
  generation:
    algorithm:
      genetics:
        populationSize: 2
        crossover-rate: 0.8
        tournament-selection-size: 5
        elite-chromosomes-number: 2
        mutation-rate: 0.5
