server:
  port: 8081

university:
  academicHoursPerDay: 2
  daysPerWeek: 2

timetable:
  generation:
    algorithm:
      genetics:
        populationSize: 100
        crossover-rate: 0.9
        tournament-selection-size: 5
        elite-chromosomes-number: 1
        mutation-rate: 0.1
