server:
  port: 8081

university:
  academicHoursPerDay: 3
  daysPerWeek: 5
  academicWeeksPerYear: 21
  classDuration: PT60M
  classStartTimes: >
    09:00,
    10:00,
    11:00

timetable:
  generation:
    algorithm:
      genetics:
        populationSize: 2
        crossover-rate: 0.8
        tournament-selection-size: 5
        elite-chromosomes-number: 2
        mutation-rate: 0.5
