server:
  port: 8081

university:
  daysPerWeek: 5
  academicWeeks: 2
  classDuration: PT60M
  secondShiftStartTimeslot: 4
  classStartTimes: >
    09:00,
    10:00,
    11:00,
    12:00,
    13:00,
    14:00

timetable:
  generation:
    algorithm:
      genetics:
        populationSize: 2
        crossover-rate: 0.8
        tournament-selection-size: 5
        elite-chromosomes-number: 2
        mutation-rate: 0.5
